### ISSUE TITLE
Error thrown at openBrowser.js:35

### ISSUE THREAD

**Issue by Kimeiga** [okwolf/srvs#6]
Occurs after `npm i -g srvs`, and then `srvs`, or `npx srvs`, or with `npm start`/`yarn start` with script added to `package.json`.

Environment: **WSL Windows 10**

Not really sure what is the cause

```bash
root@Iaye:/mnt/c/Users/Kimeiga/Github/muzik# npx srvs --docRoot=.
srvs v0.3.1
Available on:
  http://192.168.1.10:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
Error: spawn xdg-open ENOENT
^C
root@Iaye:/mnt/c/Users/Kimeiga/Github/muzik# srvs
srvs v0.3.1
Available on:
  http://192.168.1.10:8080
  http://127.0.0.1:8080
Hit CTRL-C to stop the server
/usr/local/lib/node_modules/srvs/src/client/openBrowser.js:35
    throw new Error(error);
    ^

Error: Error: spawn xdg-open ENOENT
    at ChildProcess.browser.once.error (/usr/local/lib/node_modules/srvs/src/client/openBrowser.js:35:11)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:233:12)
    at onErrorNT (internal/child_process.js:404:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
root@Iaye:/mnt/c/Users/Kimeiga/Github/muzik#
```

**Comment by Kimeiga** [comment]
running with `npx srvs` still works, but Google font doesn't load via `@import` on css file (but doesn't on http-server either). And it does with the `<link>` Google provides for html

**Comment by okwolf** [comment]
This is because with WSL `srvs` thinks you are running in Linux and uses the command `xdg-open`, which seems to have some known issues in that environment. You may want to read up more on this:
- https://superuser.com/questions/1262977/open-browser-in-host-system-from-windows-subsystem-for-linux
- https://www.reddit.com/r/bashonubuntuonwindows/comments/79hghw/how_to_use_xdgopen_with_a_windows_browser

In the future, there may be another option by disabling auto open #5.

**Comment by Kimeiga** [comment]
yeah i think you're right. I couldn't fix it in WSL with `export BROWSER`, but I could get it to work in CMD!
